version: '3.2'

services:
  traefik:
    image: traefik:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./traefik/acme:/acme
    deploy:
      replicas: 1
    environment:
      - GODADDY_API_KEY=$WT_GODADDY_API_KEY
      - GODADDY_API_SECRET=$WT_GODADDY_API_SECRET

  mongo:
    image: mongo:3.2
    networks:
      - mongo
    volumes:
      - mongo-data:/data/db
      - mongo-cfg:/data/configdb
    deploy:
      replicas: 1

  girder:
    image: wholetale/girder:latest
    networks:
      - traefik-net
      - celery
      - mongo
    volumes:
      - ./volumes:/tmp/data
      - ./girder/girder.local.cfg:/girder/girder/conf/girder.local.cfg
      - ./src/wholetale:/girder/plugins/wholetale
      - ./src/cis:/girder/plugins/cis
      - ./src/wt_data_manager:/girder/plugins/wt_data_manager
      - ./src/wt_home_dir:/girder/plugins/wt_home_dir
      - ./src/wt_versioning:/girder/plugins/wt_versioning
      - ./src/globus_handler:/girder/plugins/globus_handler
      - ./src/virtual_resources:/girder/plugins/virtual_resources
      - ./src/gwvolman:/gwvolman
      - ./src/girderfs:/girderfs
    environment:
      - DOMAIN=local.wholetale.org
      - DASHBOARD_URL=https://dashboard.local.wholetale.org
      - GOSU_USER=girder:girder
      - "GOSU_CHOWN=/tmp/data"
      - DATAONE_URL=https://cn-stage-2.test.dataone.org/cn
    deploy:
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:girder.local.wholetale.org"
        - "traefik.port=8080"
        - "traefik.enable=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=https"

  redis:
    image: redis:4-stretch
    networks:
      - celery
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  dashboard_old:
    image: wholetale/dashboardproxy:latest
    # build: ./dashboard_local
    networks:
      - traefik-net
    environment:
      - GIRDER_API_URL=https://girder.local.wholetale.org
      - AUTH_PROVIDER=Globus
      - DATAONE_URL=https://cn-stage-2.test.dataone.org
      - DASHBOARD_DEV=true
    volumes:
      - ./src/dashboard/dist:/srv/dashboard
    deploy:
      replicas: 1
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:legacy.local.wholetale.org"
        - "traefik.enable=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=https"

  dashboard:
    image: wholetale/ngx-dashboard:latest
    networks:
      - traefik-net
    environment:
      - GIRDER_API_URL=https://girder.local.wholetale.org
      - AUTH_PROVIDER=Globus
      - DATAONE_URL=https://cn-stage-2.test.dataone.org
      - DASHBOARD_DEV=true
    deploy:
      replicas: 1
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:dashboard.local.wholetale.org"
        - "traefik.enable=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=https"
    volumes:
      - ./src/ngx-dashboard/dist/browser/:/usr/share/nginx/html/

  registry:
    image: registry:2.6
    networks:
      - traefik-net
      - celery
    volumes:
      - ./registry:/var/lib/registry
      - ./registry/auth:/auth:ro
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/registry.password
    deploy:
      replicas: 1
      labels:
        - "traefik.port=5000"
        - "traefik.frontend.rule=Host:registry.local.wholetale.org"
        - "traefik.enable=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=https"
  
  ui:
    image: xarthisius/cis-ui
    networks:
      - traefik-net
    deploy:
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:ui.local.wholetale.org"
        - "traefik.port=80"
        - "traefik.enable=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.frontend.passHostHeader=true"
    environment:
      - DOMAIN=local.wholetale.org
      - GIRDER_URL=https://girder.local.wholetale.org

#  celery_worker:
#    image: wholetale/gwvolman
#    networks:
#      - celery
#    labels:
#      - "traefik.enable=false"
#    environment:
#      - GIRDER_API_URL=https://girder.local.wholetale.org/api/v1
#      - HOSTDIR=/host
#      - DOMAIN=local.wholetale.org
#      - TRAEFIK_NETWORK=wt_traefik-net
#      - TRAEFIK_ENTRYPOINT=https
#      - REGISTRY_USER=fido
#      - REGISTRY_URL=https://registry.local.wholetale.org
#      - REGISTRY_PASS=secretpass
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /:/host
#      - /var/cache/davfs2:/var/cache/davfs2
#      - /run/mount.davfs:/run/mount.davfs
#    cap_add:
#      - SYS_ADMIN
#      - SYS_PTRACE
#    devices:
#      - /dev/fuse:/dev/fuse
#    command: -Q manager,celery,xa3bl9runqzk8dgbl5gc6nlnq --hostname=xa3bl9runqzk8dgbl5gc6nlnq


networks:
  traefik-net:
    driver: overlay
  mongo:
    driver: overlay
  celery:
    driver: overlay
    attachable: true

volumes:
  mongo-data: {}
  mongo-cfg: {}
